---
name: Acme-MirrorTracer
version: 2009.051914390009
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Do nothing.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Acme::MirrorTracer:
    file: lib/Acme/MirrorTracer.pm
    version: 2009.051914390009
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
